/* eslint global-require: 0 */
export const iconData = [
  {
    icon: 'apple',
  },
  {
    icon: 'banana',
  },
  {
    icon: 'belgianfries',
  },
  {
    icon: 'birthday',
  },
  {
    icon: 'boat',
  },
  {
    icon: 'burger',
  },
  {
    icon: 'cadillac',
  },
  {
    icon: 'candy1',
  },
  {
    icon: 'candy2',
  },
  {
    icon: 'cherry',
  },
  {
    icon: 'christmas',
  },
  {
    icon: 'cloudy',
  },
  {
    icon: 'congrat1',
  },
  {
    icon: 'congrat2',
  },
  {
    icon: 'diamond',
  },
  {
    icon: 'dock',
  },
  {
    icon: 'doll',
  },
  {
    icon: 'donut',
  },
  {
    icon: 'eggplant',
  },
  {
    icon: 'emerald',
  },
  {
    icon: 'firefighter',
  },
  {
    icon: 'flowers',
  },
  {
    icon: 'goodmorning',
  },
  {
    icon: 'goodnight',
  },
  {
    icon: 'gun',
  },
  {
    icon: 'orange',
  },
  {
    icon: 'party',
  },
  {
    icon: 'pizza',
  },
  {
    icon: 'plane',
  },
  {
    icon: 'playstation',
  },
  {
    icon: 'popcorn',
  },
  {
    icon: 'present1',
  },
  {
    icon: 'present2',
  },
  {
    icon: 'rainbow',
  },
  {
    icon: 'rainy',
  },
  {
    icon: 'ruby',
  },
  {
    icon: 'snowy',
  },
  {
    icon: 'soda',
  },
  {
    icon: 'strawberry',
  },
  {
    icon: 'sunglass',
  },
  {
    icon: 'tooMuchTouch',
  },
  {
    icon: 'watermelon',
  },
];

export const iconVideos = {
  alive: require('assets/icons/neutre/alive.mp4'),
  apple: require('assets/icons/neutre/apple.mp4'),
  banana: require('assets/icons/neutre/banana.mp4'),
  belgianfries: require('assets/icons/neutre/belgianfries.mp4'),
  birthday: require('assets/icons/neutre/birthday.mp4'),
  boat: require('assets/icons/neutre/boat.mp4'),
  burger: require('assets/icons/neutre/burger.mp4'),
  cadillac: require('assets/icons/neutre/cadillac.mp4'),
  candy1: require('assets/icons/neutre/candy1.mp4'),
  candy2: require('assets/icons/neutre/candy2.mp4'),
  cherry: require('assets/icons/neutre/cherry.mp4'),
  christmas: require('assets/icons/neutre/christmas.mp4'),
  cloudy: require('assets/icons/neutre/cloudy.mp4'),
  coin1ct: require('assets/icons/neutre/coin1ct.mp4'),
  coin1e: require('assets/icons/neutre/coin1e.mp4'),
  coin2cts: require('assets/icons/neutre/coin2cts.mp4'),
  coin2e: require('assets/icons/neutre/coin2e.mp4'),
  coin5cts: require('assets/icons/neutre/coin5cts.mp4'),
  coin20cts: require('assets/icons/neutre/coin20cts.mp4'),
  coin50cts: require('assets/icons/neutre/coin50cts.mp4'),
  congrat1: require('assets/icons/neutre/congrat1.mp4'),
  congrat2: require('assets/icons/neutre/congrat2.mp4'),
  diamond: require('assets/icons/neutre/diamond.mp4'),
  dock: require('assets/icons/neutre/dock.mp4'),
  doll: require('assets/icons/neutre/doll.mp4'),
  donut: require('assets/icons/neutre/donut.mp4'),
  eggplant: require('assets/icons/neutre/eggplant.mp4'),
  emerald: require('assets/icons/neutre/emerald.mp4'),
  firefighter: require('assets/icons/neutre/firefighter.mp4'),
  flowers: require('assets/icons/neutre/flowers.mp4'),
  goodmorning: require('assets/icons/neutre/goodmorning.mp4'),
  goodnight: require('assets/icons/neutre/goodnight.mp4'),
  gun: require('assets/icons/neutre/gun.mp4'),
  notifClose: require('assets/icons/neutre/notifClose.mp4'),
  notifOpen: require('assets/icons/neutre/notifOpen.mp4'),
  orange: require('assets/icons/neutre/orange.mp4'),
  party: require('assets/icons/neutre/party.mp4'),
  pizza: require('assets/icons/neutre/pizza.mp4'),
  plane: require('assets/icons/neutre/plane.mp4'),
  playstation: require('assets/icons/neutre/playstation.mp4'),
  popcorn: require('assets/icons/neutre/popcorn.mp4'),
  present1: require('assets/icons/neutre/present1.mp4'),
  present2: require('assets/icons/neutre/present2.mp4'),
  rainbow: require('assets/icons/neutre/rainbow.mp4'),
  rainy: require('assets/icons/neutre/rainy.mp4'),
  ruby: require('assets/icons/neutre/ruby.mp4'),
  snowy: require('assets/icons/neutre/snowy.mp4'),
  soda: require('assets/icons/neutre/soda.mp4'),
  strawberry: require('assets/icons/neutre/strawberry.mp4'),
  sunglass: require('assets/icons/neutre/sunglass.mp4'),
  tooMuchTouch: require('assets/icons/neutre/tooMuchTouch.mp4'),
  transition1: require('assets/icons/neutre/transition1.mp4'),
  watermelon: require('assets/icons/neutre/watermelon.mp4'),

  alive_blanc: require('assets/icons/blanc/alive.mp4'),
  apple_blanc: require('assets/icons/blanc/apple.mp4'),
  banana_blanc: require('assets/icons/blanc/banana.mp4'),
  belgianfries_blanc: require('assets/icons/blanc/belgianfries.mp4'),
  birthday_blanc: require('assets/icons/blanc/birthday.mp4'),
  boat_blanc: require('assets/icons/blanc/boat.mp4'),
  burger_blanc: require('assets/icons/blanc/burger.mp4'),
  cadillac_blanc: require('assets/icons/blanc/cadillac.mp4'),
  candy1_blanc: require('assets/icons/blanc/candy1.mp4'),
  candy2_blanc: require('assets/icons/blanc/candy2.mp4'),
  cherry_blanc: require('assets/icons/blanc/cherry.mp4'),
  christmas_blanc: require('assets/icons/blanc/christmas.mp4'),
  cloudy_blanc: require('assets/icons/blanc/cloudy.mp4'),
  coin1ct_blanc: require('assets/icons/blanc/coin1ct.mp4'),
  coin1e_blanc: require('assets/icons/blanc/coin1e.mp4'),
  coin2cts_blanc: require('assets/icons/blanc/coin2cts.mp4'),
  coin2e_blanc: require('assets/icons/blanc/coin2e.mp4'),
  coin5cts_blanc: require('assets/icons/blanc/coin5cts.mp4'),
  coin20cts_blanc: require('assets/icons/blanc/coin20cts.mp4'),
  coin50cts_blanc: require('assets/icons/blanc/coin50cts.mp4'),
  congrat1_blanc: require('assets/icons/blanc/congrat1.mp4'),
  congrat2_blanc: require('assets/icons/blanc/congrat2.mp4'),
  diamond_blanc: require('assets/icons/blanc/diamond.mp4'),
  dock_blanc: require('assets/icons/blanc/dock.mp4'),
  doll_blanc: require('assets/icons/blanc/doll.mp4'),
  donut_blanc: require('assets/icons/blanc/donut.mp4'),
  eggplant_blanc: require('assets/icons/blanc/eggplant.mp4'),
  emerald_blanc: require('assets/icons/blanc/emerald.mp4'),
  firefighter_blanc: require('assets/icons/blanc/firefighter.mp4'),
  flowers_blanc: require('assets/icons/blanc/flowers.mp4'),
  goodmorning_blanc: require('assets/icons/blanc/goodmorning.mp4'),
  goodnight_blanc: require('assets/icons/blanc/goodnight.mp4'),
  gun_blanc: require('assets/icons/blanc/gun.mp4'),
  notifClose_blanc: require('assets/icons/blanc/notifClose.mp4'),
  notifOpen_blanc: require('assets/icons/blanc/notifOpen.mp4'),
  orange_blanc: require('assets/icons/blanc/orange.mp4'),
  party_blanc: require('assets/icons/blanc/party.mp4'),
  pizza_blanc: require('assets/icons/blanc/pizza.mp4'),
  plane_blanc: require('assets/icons/blanc/plane.mp4'),
  playstation_blanc: require('assets/icons/blanc/playstation.mp4'),
  popcorn_blanc: require('assets/icons/blanc/popcorn.mp4'),
  present1_blanc: require('assets/icons/blanc/present1.mp4'),
  present2_blanc: require('assets/icons/blanc/present2.mp4'),
  rainbow_blanc: require('assets/icons/blanc/rainbow.mp4'),
  rainy_blanc: require('assets/icons/blanc/rainy.mp4'),
  ruby_blanc: require('assets/icons/blanc/ruby.mp4'),
  snowy_blanc: require('assets/icons/blanc/snowy.mp4'),
  soda_blanc: require('assets/icons/blanc/soda.mp4'),
  strawberry_blanc: require('assets/icons/blanc/strawberry.mp4'),
  sunglass_blanc: require('assets/icons/blanc/sunglass.mp4'),
  tooMuchTouch_blanc: require('assets/icons/blanc/tooMuchTouch.mp4'),
  transition1_blanc: require('assets/icons/blanc/transition1.mp4'),
  watermelon_blanc: require('assets/icons/blanc/watermelon.mp4'),

  alive_bleu: require('assets/icons/bleu/alive.mp4'),
  apple_bleu: require('assets/icons/bleu/apple.mp4'),
  banana_bleu: require('assets/icons/bleu/banana.mp4'),
  belgianfries_bleu: require('assets/icons/bleu/belgianfries.mp4'),
  birthday_bleu: require('assets/icons/bleu/birthday.mp4'),
  boat_bleu: require('assets/icons/bleu/boat.mp4'),
  burger_bleu: require('assets/icons/bleu/burger.mp4'),
  cadillac_bleu: require('assets/icons/bleu/cadillac.mp4'),
  candy1_bleu: require('assets/icons/bleu/candy1.mp4'),
  candy2_bleu: require('assets/icons/bleu/candy2.mp4'),
  cherry_bleu: require('assets/icons/bleu/cherry.mp4'),
  christmas_bleu: require('assets/icons/bleu/christmas.mp4'),
  cloudy_bleu: require('assets/icons/bleu/cloudy.mp4'),
  coin1ct_bleu: require('assets/icons/bleu/coin1ct.mp4'),
  coin1e_bleu: require('assets/icons/bleu/coin1e.mp4'),
  coin2cts_bleu: require('assets/icons/bleu/coin2cts.mp4'),
  coin2e_bleu: require('assets/icons/bleu/coin2e.mp4'),
  coin5cts_bleu: require('assets/icons/bleu/coin5cts.mp4'),
  coin20cts_bleu: require('assets/icons/bleu/coin20cts.mp4'),
  coin50cts_bleu: require('assets/icons/bleu/coin50cts.mp4'),
  congrat1_bleu: require('assets/icons/bleu/congrat1.mp4'),
  congrat2_bleu: require('assets/icons/bleu/congrat2.mp4'),
  diamond_bleu: require('assets/icons/bleu/diamond.mp4'),
  dock_bleu: require('assets/icons/bleu/dock.mp4'),
  doll_bleu: require('assets/icons/bleu/doll.mp4'),
  donut_bleu: require('assets/icons/bleu/donut.mp4'),
  eggplant_bleu: require('assets/icons/bleu/eggplant.mp4'),
  emerald_bleu: require('assets/icons/bleu/emerald.mp4'),
  firefighter_bleu: require('assets/icons/bleu/firefighter.mp4'),
  flowers_bleu: require('assets/icons/bleu/flowers.mp4'),
  goodmorning_bleu: require('assets/icons/bleu/goodmorning.mp4'),
  goodnight_bleu: require('assets/icons/bleu/goodnight.mp4'),
  gun_bleu: require('assets/icons/bleu/gun.mp4'),
  notifClose_bleu: require('assets/icons/bleu/notifClose.mp4'),
  notifOpen_bleu: require('assets/icons/bleu/notifOpen.mp4'),
  orange_bleu: require('assets/icons/bleu/orange.mp4'),
  party_bleu: require('assets/icons/bleu/party.mp4'),
  pizza_bleu: require('assets/icons/bleu/pizza.mp4'),
  plane_bleu: require('assets/icons/bleu/plane.mp4'),
  playstation_bleu: require('assets/icons/bleu/playstation.mp4'),
  popcorn_bleu: require('assets/icons/bleu/popcorn.mp4'),
  present1_bleu: require('assets/icons/bleu/present1.mp4'),
  present2_bleu: require('assets/icons/bleu/present2.mp4'),
  rainbow_bleu: require('assets/icons/bleu/rainbow.mp4'),
  rainy_bleu: require('assets/icons/bleu/rainy.mp4'),
  ruby_bleu: require('assets/icons/bleu/ruby.mp4'),
  snowy_bleu: require('assets/icons/bleu/snowy.mp4'),
  soda_bleu: require('assets/icons/bleu/soda.mp4'),
  strawberry_bleu: require('assets/icons/bleu/strawberry.mp4'),
  sunglass_bleu: require('assets/icons/bleu/sunglass.mp4'),
  tooMuchTouch_bleu: require('assets/icons/bleu/tooMuchTouch.mp4'),
  transition1_bleu: require('assets/icons/bleu/transition1.mp4'),
  watermelon_bleu: require('assets/icons/bleu/watermelon.mp4'),

  alive_orange: require('assets/icons/orange/alive.mp4'),
  apple_orange: require('assets/icons/orange/apple.mp4'),
  banana_orange: require('assets/icons/orange/banana.mp4'),
  belgianfries_orange: require('assets/icons/orange/belgianfries.mp4'),
  birthday_orange: require('assets/icons/orange/birthday.mp4'),
  boat_orange: require('assets/icons/orange/boat.mp4'),
  burger_orange: require('assets/icons/orange/burger.mp4'),
  cadillac_orange: require('assets/icons/orange/cadillac.mp4'),
  candy1_orange: require('assets/icons/orange/candy1.mp4'),
  candy2_orange: require('assets/icons/orange/candy2.mp4'),
  cherry_orange: require('assets/icons/orange/cherry.mp4'),
  christmas_orange: require('assets/icons/orange/christmas.mp4'),
  cloudy_orange: require('assets/icons/orange/cloudy.mp4'),
  coin1ct_orange: require('assets/icons/orange/coin1ct.mp4'),
  coin1e_orange: require('assets/icons/orange/coin1e.mp4'),
  coin2cts_orange: require('assets/icons/orange/coin2cts.mp4'),
  coin2e_orange: require('assets/icons/orange/coin2e.mp4'),
  coin5cts_orange: require('assets/icons/orange/coin5cts.mp4'),
  coin20cts_orange: require('assets/icons/orange/coin20cts.mp4'),
  coin50cts_orange: require('assets/icons/orange/coin50cts.mp4'),
  congrat1_orange: require('assets/icons/orange/congrat1.mp4'),
  congrat2_orange: require('assets/icons/orange/congrat2.mp4'),
  diamond_orange: require('assets/icons/orange/diamond.mp4'),
  dock_orange: require('assets/icons/orange/dock.mp4'),
  doll_orange: require('assets/icons/orange/doll.mp4'),
  donut_orange: require('assets/icons/orange/donut.mp4'),
  eggplant_orange: require('assets/icons/orange/eggplant.mp4'),
  emerald_orange: require('assets/icons/orange/emerald.mp4'),
  firefighter_orange: require('assets/icons/orange/firefighter.mp4'),
  flowers_orange: require('assets/icons/orange/flowers.mp4'),
  goodmorning_orange: require('assets/icons/orange/goodmorning.mp4'),
  goodnight_orange: require('assets/icons/orange/goodnight.mp4'),
  gun_orange: require('assets/icons/orange/gun.mp4'),
  notifClose_orange: require('assets/icons/orange/notifClose.mp4'),
  notifOpen_orange: require('assets/icons/orange/notifOpen.mp4'),
  orange_orange: require('assets/icons/orange/orange.mp4'),
  party_orange: require('assets/icons/orange/party.mp4'),
  pizza_orange: require('assets/icons/orange/pizza.mp4'),
  plane_orange: require('assets/icons/orange/plane.mp4'),
  playstation_orange: require('assets/icons/orange/playstation.mp4'),
  popcorn_orange: require('assets/icons/orange/popcorn.mp4'),
  present1_orange: require('assets/icons/orange/present1.mp4'),
  present2_orange: require('assets/icons/orange/present2.mp4'),
  rainbow_orange: require('assets/icons/orange/rainbow.mp4'),
  rainy_orange: require('assets/icons/orange/rainy.mp4'),
  ruby_orange: require('assets/icons/orange/ruby.mp4'),
  snowy_orange: require('assets/icons/orange/snowy.mp4'),
  soda_orange: require('assets/icons/orange/soda.mp4'),
  strawberry_orange: require('assets/icons/orange/strawberry.mp4'),
  sunglass_orange: require('assets/icons/orange/sunglass.mp4'),
  tooMuchTouch_orange: require('assets/icons/orange/tooMuchTouch.mp4'),
  transition1_orange: require('assets/icons/orange/transition1.mp4'),
  watermelon_orange: require('assets/icons/orange/watermelon.mp4'),

  alive_rose: require('assets/icons/rose/alive.mp4'),
  apple_rose: require('assets/icons/rose/apple.mp4'),
  banana_rose: require('assets/icons/rose/banana.mp4'),
  belgianfries_rose: require('assets/icons/rose/belgianfries.mp4'),
  birthday_rose: require('assets/icons/rose/birthday.mp4'),
  boat_rose: require('assets/icons/rose/boat.mp4'),
  burger_rose: require('assets/icons/rose/burger.mp4'),
  cadillac_rose: require('assets/icons/rose/cadillac.mp4'),
  candy1_rose: require('assets/icons/rose/candy1.mp4'),
  candy2_rose: require('assets/icons/rose/candy2.mp4'),
  cherry_rose: require('assets/icons/rose/cherry.mp4'),
  christmas_rose: require('assets/icons/rose/christmas.mp4'),
  cloudy_rose: require('assets/icons/rose/cloudy.mp4'),
  coin1ct_rose: require('assets/icons/rose/coin1ct.mp4'),
  coin1e_rose: require('assets/icons/rose/coin1e.mp4'),
  coin2cts_rose: require('assets/icons/rose/coin2cts.mp4'),
  coin2e_rose: require('assets/icons/rose/coin2e.mp4'),
  coin5cts_rose: require('assets/icons/rose/coin5cts.mp4'),
  coin20cts_rose: require('assets/icons/rose/coin20cts.mp4'),
  coin50cts_rose: require('assets/icons/rose/coin50cts.mp4'),
  congrat1_rose: require('assets/icons/rose/congrat1.mp4'),
  congrat2_rose: require('assets/icons/rose/congrat2.mp4'),
  diamond_rose: require('assets/icons/rose/diamond.mp4'),
  dock_rose: require('assets/icons/rose/dock.mp4'),
  doll_rose: require('assets/icons/rose/doll.mp4'),
  donut_rose: require('assets/icons/rose/donut.mp4'),
  eggplant_rose: require('assets/icons/rose/eggplant.mp4'),
  emerald_rose: require('assets/icons/rose/emerald.mp4'),
  firefighter_rose: require('assets/icons/rose/firefighter.mp4'),
  flowers_rose: require('assets/icons/rose/flowers.mp4'),
  goodmorning_rose: require('assets/icons/rose/goodmorning.mp4'),
  goodnight_rose: require('assets/icons/rose/goodnight.mp4'),
  gun_rose: require('assets/icons/rose/gun.mp4'),
  notifClose_rose: require('assets/icons/rose/notifClose.mp4'),
  notifOpen_rose: require('assets/icons/rose/notifOpen.mp4'),
  orange_rose: require('assets/icons/rose/orange.mp4'),
  party_rose: require('assets/icons/rose/party.mp4'),
  pizza_rose: require('assets/icons/rose/pizza.mp4'),
  plane_rose: require('assets/icons/rose/plane.mp4'),
  playstation_rose: require('assets/icons/rose/playstation.mp4'),
  popcorn_rose: require('assets/icons/rose/popcorn.mp4'),
  present1_rose: require('assets/icons/rose/present1.mp4'),
  present2_rose: require('assets/icons/rose/present2.mp4'),
  rainbow_rose: require('assets/icons/rose/rainbow.mp4'),
  rainy_rose: require('assets/icons/rose/rainy.mp4'),
  ruby_rose: require('assets/icons/rose/ruby.mp4'),
  snowy_rose: require('assets/icons/rose/snowy.mp4'),
  soda_rose: require('assets/icons/rose/soda.mp4'),
  strawberry_rose: require('assets/icons/rose/strawberry.mp4'),
  sunglass_rose: require('assets/icons/rose/sunglass.mp4'),
  tooMuchTouch_rose: require('assets/icons/rose/tooMuchTouch.mp4'),
  transition1_rose: require('assets/icons/rose/transition1.mp4'),
  watermelon_rose: require('assets/icons/rose/watermelon.mp4'),

  alive_violet: require('assets/icons/violet/alive.mp4'),
  apple_violet: require('assets/icons/violet/apple.mp4'),
  banana_violet: require('assets/icons/violet/banana.mp4'),
  belgianfries_violet: require('assets/icons/violet/belgianfries.mp4'),
  birthday_violet: require('assets/icons/violet/birthday.mp4'),
  boat_violet: require('assets/icons/violet/boat.mp4'),
  burger_violet: require('assets/icons/violet/burger.mp4'),
  cadillac_violet: require('assets/icons/violet/cadillac.mp4'),
  candy1_violet: require('assets/icons/violet/candy1.mp4'),
  candy2_violet: require('assets/icons/violet/candy2.mp4'),
  cherry_violet: require('assets/icons/violet/cherry.mp4'),
  christmas_violet: require('assets/icons/violet/christmas.mp4'),
  cloudy_violet: require('assets/icons/violet/cloudy.mp4'),
  coin1ct_violet: require('assets/icons/violet/coin1ct.mp4'),
  coin1e_violet: require('assets/icons/violet/coin1e.mp4'),
  coin2cts_violet: require('assets/icons/violet/coin2cts.mp4'),
  coin2e_violet: require('assets/icons/violet/coin2e.mp4'),
  coin5cts_violet: require('assets/icons/violet/coin5cts.mp4'),
  coin20cts_violet: require('assets/icons/violet/coin20cts.mp4'),
  coin50cts_violet: require('assets/icons/violet/coin50cts.mp4'),
  congrat1_violet: require('assets/icons/violet/congrat1.mp4'),
  congrat2_violet: require('assets/icons/violet/congrat2.mp4'),
  diamond_violet: require('assets/icons/violet/diamond.mp4'),
  dock_violet: require('assets/icons/violet/dock.mp4'),
  doll_violet: require('assets/icons/violet/doll.mp4'),
  donut_violet: require('assets/icons/violet/donut.mp4'),
  eggplant_violet: require('assets/icons/violet/eggplant.mp4'),
  emerald_violet: require('assets/icons/violet/emerald.mp4'),
  firefighter_violet: require('assets/icons/violet/firefighter.mp4'),
  flowers_violet: require('assets/icons/violet/flowers.mp4'),
  goodmorning_violet: require('assets/icons/violet/goodmorning.mp4'),
  goodnight_violet: require('assets/icons/violet/goodnight.mp4'),
  gun_violet: require('assets/icons/violet/gun.mp4'),
  notifClose_violet: require('assets/icons/violet/notifClose.mp4'),
  notifOpen_violet: require('assets/icons/violet/notifOpen.mp4'),
  orange_violet: require('assets/icons/violet/orange.mp4'),
  party_violet: require('assets/icons/violet/party.mp4'),
  pizza_violet: require('assets/icons/violet/pizza.mp4'),
  plane_violet: require('assets/icons/violet/plane.mp4'),
  playstation_violet: require('assets/icons/violet/playstation.mp4'),
  popcorn_violet: require('assets/icons/violet/popcorn.mp4'),
  present1_violet: require('assets/icons/violet/present1.mp4'),
  present2_violet: require('assets/icons/violet/present2.mp4'),
  rainbow_violet: require('assets/icons/violet/rainbow.mp4'),
  rainy_violet: require('assets/icons/violet/rainy.mp4'),
  ruby_violet: require('assets/icons/violet/ruby.mp4'),
  snowy_violet: require('assets/icons/violet/snowy.mp4'),
  soda_violet: require('assets/icons/violet/soda.mp4'),
  strawberry_violet: require('assets/icons/violet/strawberry.mp4'),
  sunglass_violet: require('assets/icons/violet/sunglass.mp4'),
  tooMuchTouch_violet: require('assets/icons/violet/tooMuchTouch.mp4'),
  transition1_violet: require('assets/icons/violet/transition1.mp4'),
  watermelon_violet: require('assets/icons/violet/watermelon.mp4'),
};
