export const TOGGLE_BG_SELECTOR = 'TOGGLE_BG_SELECTOR';
export const SET_BACKGROUND = 'SET_BACKGROUND';
export const RESET_APP = 'RESET_APP';
export const RESET_APP_ERRRORS = 'RESET_APP_ERRRORS';

export const CHECK_USER_EXIST = 'CHECK_USER_EXIST';
export const SET_USER_EXIST = 'SET_USER_EXIST';
export const CLEAR_USER_EXIST = 'CLEAR_USER_EXIST';

export const SET_ANDROID_RIPPLE = 'SET_ANDROID_RIPPLE';

export const SET_PIGGY_INFOS = 'SET_PIGGY_INFOS';
