export const REGISTER_START = 'REGISTER_START';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GOOGLE_REGISTER_START = 'GOOGLE_REGISTER_START';
export const GOOGLE_REGISTER_ERROR = 'GOOGLE_REGISTER_ERROR';

export const GOOGLE_LOGIN_START = 'GOOGLE_LOGIN_START';
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR';

export const FB_REGISTER_START = 'FB_REGISTER_START';
export const FB_REGISTER_ERROR = 'FB_REGISTER_ERROR';

export const FB_LOGIN_START = 'FB_LOGIN_START';
export const FB_LOGIN_ERROR = 'FB_LOGIN_ERROR';

export const RESET_ALL_ERRORS = 'RESET_ALL_ERRORS';

// Reset Password
export const RESET_PWD_START = 'RESET_PWD_START';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_ERROR = 'RESET_PWD_ERROR';
export const RESET_CODE_START = 'RESET_CODE_START';
export const CHANGE_PWD_START = 'CHANGE_PWD_START';
export const RESET_ERROR = 'RESET_ERROR';
