export const GET_UNREAD_NOTIFICATION = 'GET_UNREAD_NOTIFICATION';
export const START_WEBSOCKET = 'START_WEBSOCKET';

export const SET_NOTIFICATION_TO_READ = 'SET_NOTIFICATION_TO_READ';
export const RESET_NOTIFICATION_SUCCESS = 'RESET_NOTIFICATION_SUCCESS';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';

export const SET_ERROR = 'SET_ERROR';
