export const SAVE_CARD = 'SAVE_CARD';
export const SAVE_CARD_SUCCESS = 'SAVE_CARD_SUCCESS';
export const SAVE_CARD_ERROR = 'SAVE_CARD_ERROR';
export const CLEAR_CARD_ERROR = 'CLEAR_CARD_ERROR';

export const SAVE_BANK_ACCOUNT = 'SAVE_BANK_ACCOUNT';

export const CREATE_PAY_USER = 'CREATE_PAY_USER';
export const CREATE_PAY_USER_ERROR = 'CREATE_PAY_USER_ERROR';

export const SET_CARD_ID = 'SET_CARD_ID';
export const SEND_CARD_ID = 'SEND_CARD_ID';

export const SET_SELECTED_BANK_ACCOUNT = 'SET_SELECTED_BANK_ACCOUNT';

export const SET_PAYMENTMEANS_DATA_PARENT = 'SET_PAYMENTMEANS_DATA_PARENT';
export const SET_PAYMENTMEANS_DATA_CHILD = 'SET_PAYMENTMEANS_DATA_CHILD';

export const START_WEBSOCKET = 'START_WEBSOCKET';
