export const SET_PIGGY_BANK = 'SET_PIGGY_BANK';
export const SET_PIGGY_BANK_FAILURE = 'SET_PIGGY_BANK_FAILURE';
export const CREATE_PIGGY_BANK = 'CREATE_PIGGY_BANK';
export const INIT_PIGGY_BANK = 'INIT_PIGGY_BANK';
export const SET_PIGGY_BANK_AMOUNT = 'SET_PIGGY_BANK_AMOUNT';
