export const EDIT_PROFILE_CHILD = 'EDIT_PROFILE_CHILD';
export const CHANGE_PROFILE_CHILD = 'CHANGE_PROFILE_CHILD';
export const SET_PROFILE_CHILD = 'SET_PROFILE_CHILD';
export const SET_PROFILE_PARENT = 'SET_PROFILE_PARENT';
export const SET_PROFILE_CHILD_AMOUNT = 'SET_PROFILE_CHILD_AMOUNT';
export const START_WEBSOCKET = 'START_WEBSOCKET';

export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_CHILD_PROFILE = 'EDIT_CHILD_PROFILE';
