export const GET_PROFILES_START = 'GET_PROFILES';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAILURE = 'GET_PROFILES_FAILURE';

export const GET_PAYMENT_MEANS_START = 'GET_PAYMENT_MEANS_START';
export const GET_PAYMENT_MEANS_SUCCESS = 'GET_PAYMENT_MEANS_SUCCESS';
export const GET_PAYMENT_MEANS_FAILURE = 'GET_PAYMENT_MEANS_FAILURE';

export const GET_PURCHASES_START = 'GET_PURCHASES_START';
export const GET_PURCHASES_SUCCESS = 'GET_PURCHASES_SUCCESS';
export const GET_PURCHASES_FAILURE = 'GET_PURCHASES_FAILURE';
