export const SEND_PAYIN_TO_SERVER = 'SEND_PAYIN_TO_SERVER';
export const TRANSFERT_ERROR = 'TRANSFERT_ERROR';
export const TRANSFERT_SUCCESS = 'TRANSFERT_SUCCESS';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const TRANSFERT_INITIALIZE = 'TRANSFERT_INITIALIZE';
