export const START_EDIT_USER = 'START_EDIT_USER';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const SET_USER_DATAS_SUCCESS = 'SET_USER_DATAS_SUCCESS';
export const SET_USER_DATAS_FAILURE = 'SET_USER_DATAS_FAILURE';

export const SAVE_PARTIAL_REGISTER = 'SAVE_PARTIAL_REGISTER';
